### ISSUE TITLE
Release version 4.0.0

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/bixby#67]
Changes following https://github.com/samvera-labs/bixby/commit/1c227e1867da52d045546911221a932c10250261 should be tracked and prepared for a new release.

**Comment by cjcolvar** [comment]
I think this should probably be a 4.0.0 release given the big jump in rubocop version and the possible need for users to fix the style in their gems/applications.

**Comment by jrgriffiniii** [comment]
This has been released as `v4.0.0` (https://github.com/samvera/bixby/releases/tag/v4.0.0) and published to RubyGems (https://rubygems.org/gems/bixby/versions/4.0.0). I shall follow this by also publishing an announcement to the community as to the status of this new component. Thank you very much for leading this @cjcolvar, @bess, and @kelynch!
